# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-linux:

    runs-on: fedora-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    - name: Create ELF with pyinstaller
      run: |
        pyinstaller --onefile --optimize 2 --name seamless-update.elf ./seamless-update.py
    - name: Archive and Post
      uses: actions/upload-artifact@v4
      with:
        name: seamless-update-linux
        path: |
          ./dist/seamless-update.elf
    
  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    - name: Create EXE with pyinstaller
      run: |
        pyinstaller --onefile --optimize 2 --name seamless-update.exe .\seamless-update.py
    - name: Archive and Post
      uses: actions/upload-artifact@v4
      with:
        name: seamless-update-windows
        path: |
          .\dist\seamless-update.exe
        
    
